# Generated by Django 5.1.6 on 2025-03-19 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Kategoriya otasi', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
